[package]
name = "toolbox-desktop"
version = "1.0.0"
description = "跨平台桌面工具箱"
authors = ["you"]
edition = "2021"

[[bin]]
name = "toolbox-desktop"
path = "main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
